spring:
  application:
    name: service-register-center
  mandatory-file-encoding: UTF-8

logging:
  file:
    max-size: 15MB
    path: service-register-center-log
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss:SSS
  level:
    root: info

server:
  port: 10099
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
  undertow:
    accesslog:
      enabled: true
      dir: service_register_center_access_log
      pattern: common
      prefix: service_register_center_access_log.
      suffix: log
      rotate: true
management:
  endpoints:
    web:
      exposure:
        exclude: '*'
  endpoint:
    shutdown:
      enabled: true

eureka:
  instance:
    hostname: node1
  client:
    register-with-eureka: false #单台注册中心不需要注册自己 集群需要互相注册
    fetch-registry: false #获取注册列表信息 集群之间需要互相拉取注册信息
    service-url: #注册服务器地址 集群需要设置其他备份机器的注册地址
      defaultZone: http://node1:10099/eureka/
#  server:
#    enable-self-preservation: false #启用自我保护 网络抖动造成短时间大量的客户端连接不可用服务器会保持客户端连接一段时间

###########################################################################

test:
  data:
    map:
      name: InjectMapFromYAML
      url: http://injectmapfromyaml.dev
      description: How To Inject a map from a YAML File in Spring Boot

