server:
  port: 6666

spring:
  application:
    name: zuul-gateway

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://node1:10099/eureka/
zuul:
  routes: # 默认会根据注册中心中除了zuul本身外所有服务名称作为端点信息 "/feign-client/**":"feign-client"
    # 可以在开启actutor后在 /actutor/routes 路径下看到所有路由路径 s
    eureka-client-api:
      path: /eureka-client-api/**
      serviceId: eureka-client
    feign-client-api:
      path: /feign-client-api/**
      serviceId: feign-client
  ignored-patterns: #禁用掉默认的路由路径
    - /eureka-client/**
    - /feign-client/**
  ignored-headers: authKey2
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
logging:
  level:
    com.netflix: debug